name: Build Plugin

on:
  push:
    branches: [ master, ci ]    
    tags:
      - 'v*'

  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamdeck-sdk streamdeck-sdk-cli

      - name: Create venv
        run: |
          python -m venv com.mcczarny.outlookunreadcounter.sdPlugin/code/venv
          com.mcczarny.outlookunreadcounter.sdPlugin/code/venv/Scripts/pip install --upgrade pip
          com.mcczarny.outlookunreadcounter.sdPlugin/code/venv/Scripts/pip install -r com.mcczarny.outlookunreadcounter.sdPlugin/code/requirements.txt
          
      - name: Build Stream Deck plugin
        run: |
          streamdeck_sdk build -i com.mcczarny.outlookunreadcounter.sdPlugin
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.mcczarny.outlookunreadcounter.streamDeckPlugin
          path: releases/*

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*/com.mcczarny.outlookunreadcounter.streamDeckPlugin
